### PR TITLE
DDF-1356 Changed groupid from org.forgerock.commons to org.codice.for…

### PR DESCRIPTION
**Pull request by clockard**
@stustison or @shaundmorris can one of you check out these changes and merge them?

### CODE REVIEW

**Comment by stustison** [comment]
@pklinef do you think we should just blanket change all of the group ids just incase we ever need to pull anything else out of here?

**Comment by pklinef** [comment]
It might be easier to do it that way.  That is what we usually do with third party libraries in ddf-libs.

You might not want to do that on master though if you plan to pull in newer commits in the future.

**Comment by stustison** [comment]
I think it will be a pain to pull in new commits to this repo anyways since it isn't just forked from a mirror.

**Comment by pklinef** [comment]
We also need to release the snapshot as an alpha release.

**Pull request merged**
